version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:1.15.9
    ports:
      - "80:80"
      - "8080:8080"
    links:
      - phpfpm
    depends_on:
      - phpfpm
    volumes:
      - "./nginx/logs:/var/log/nginx"
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf/mime.types:/etc/nginx/mime.types"
      - "./www-backend:/var/www-backend"
      - "./www-frontend:/var/www-frontend"
    environment:
      TZ: Europe/Moscow
    restart: always

  phpfpm:
    container_name: phpfpm
    build:
      context: ./php
    working_dir: /var/www-backend
    volumes:
      - "./php/conf/php.ini:/usr/local/etc/php/php.ini"
      - "./www-backend:/var/www-backend"
    links:
      - mysql
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always

  phpmyadmin:
    container_name: myadmin
    image: nazarpc/phpmyadmin
    ports:
      - "1234:80"
    links:
      - mysql
    depends_on:
      - mysql
    restart: always

  composer:
    container_name: composer
    image: composer:latest
    command: 'true'
    volumes:
      - ./www-backend:/app
    tty: true
    restart: 'no'