version: '3.7'

volumes:
  acmesh_ssl:

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - phpfpm
    depends_on:
      - phpfpm
    volumes:
      - "./nginx/logs:/var/log/nginx"
      - "./www-backend:/var/www-backend"
      - "./www-frontend:/var/www-frontend"
      - "acmesh_ssl:/etc/nginx/ssl"
    environment:
      TZ: Europe/Moscow
      NGINX_ROOT_FRONTEND: ${NGINX_ROOT_FRONTEND}
      NGINX_ROOT_BACKEND: ${NGINX_ROOT_BACKEND}
      NGINX_SERVER_NAME_FRONTEND: ${NGINX_SERVER_NAME_FRONTEND}
      NGINX_SERVER_NAME_BACKEND: ${NGINX_SERVER_NAME_BACKEND}
      NGINX_PORT: ${NGINX_PORT}
      NGINX_SSL_CERT: ${NGINX_SSL_CERT}
    restart: always

  phpfpm:
    container_name: phpfpm
    build:
      context: ./php
    working_dir: /var/www-backend
    volumes:
      - "./php/conf/php.ini:/usr/local/etc/php/php.ini"
      - "./www-backend:/var/www-backend"
    links:
      - mysql
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always

  phpmyadmin:
    container_name: myadmin
    image: nazarpc/phpmyadmin
    ports:
      - "1234:80"
    links:
      - mysql
    depends_on:
      - mysql
    restart: always

  composer:
    container_name: composer
    image: composer:latest
    command: 'true'
    volumes:
      - "./www-backend:/app"
    tty: true
    restart: 'no'

  acme:
    container_name: acme
    image: neilpang/acme.sh
    volumes:
      - "acmesh_ssl:/var/ssl"
    depends_on:
      - nginx
    command: 'daemon --reloadcmd "docker restart nginx"'
    restart: always