version: '3.7'

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28

services:
  nginx:
    networks:
      - internal
    restart: on-failure

  phpfpm:
    container_name: phpfpm
    build:
      args:
        APP_ENV: dev
    user: 1000:1000
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
    networks:
      - internal
    restart: on-failure

  mysql:
    networks:
      - internal
    restart: on-failure

  phpmyadmin:
    networks:
      - internal
    restart: on-failure

  composer:
    user: 1000:1000
